/*DROP TABLE IF EXISTS users;
CREATE TABLE users(id UUID PRIMARY KEY NOT NULL,created TIMESTAMP NOT NULL,name VARCHAR(300) NOT NULL,email VARCHAR(150) NOT NULL,password VARCHAR(150) NOT NULL,isActive BIT NOT NULL,token UUID NOT NULL, lastLogin DATE, lastModified DATE);
DROP TABLE IF EXISTS phones;
CREATE TABLE phones(id BIGINT NOT NULL PRIMARY KEY,ts_creation TIMESTAMP NOT NULL,id_user INT NOT NULL,phone VARCHAR(300) NOT NULL,citycode VARCHAR(50) NOT NULL,countrycode VARCHAR(50) NOT NULL);
*/